List productData = [
  {
    "videoUrl": "assets/videos/video1.mp4",
    "productUrl": "https://fryaway.co/collections/all/products/fryaway-pan-fry",
    "productName": "FRYAWAY Pan Fry",
    "productDescription":
        "Pan Fry is the best solution when cooking with smaller amounts of oil.",
    "currency": "\$",
    "priceBig": "9",
    "priceSmall": ".99",
    "shipping": "",
    "taxes": "(excl. of taxes)",
    "isLiked": false,
    "likes": "423 K",
    "isSaved": false,
    "saves": "39 K",
    "shares": "16 K",
  },
  {
    "videoUrl": "assets/videos/video2.mp4",
    "productUrl":
        "https://www.amazon.com/Ofanyia-Detangler-Electric-Detangling-Purple/dp/B083LS8W9G",
    "productName": "Ofanyia Hair Detangler Brush",
    "productDescription":
        "Electric detangling Brush with Brush Cover for Wet Or Dry hair.",
    "currency": "\$",
    "priceBig": "20",
    "priceSmall": ".99",
    "shipping": "+ free shipping.",
    "taxes": "(incl. of all taxes)",
    "isLiked": false,
    "likes": "1.2 M",
    "isSaved": false,
    "saves": "70 K",
    "shares": "13 K",
  },
  {
    "videoUrl": "assets/videos/video3.mp4",
    "productUrl":
        "https://ahujasons.com/product/handloom-pure-pashmina-shawl-as00911338.html",
    "productName": "Ahujasons - Pashmina Shawl",
    "productDescription": "Handloom Pure Pashmina Shawl.",
    "currency": "₹",
    "priceBig": "235000",
    "priceSmall": "",
    "shipping": "+ free shipping.",
    "taxes": "(incl. of all taxes)",
    "isLiked": false,
    "likes": "270 K",
    "isSaved": false,
    "saves": "12 K",
    "shares": "4 K",
  },
  {
    "videoUrl": "assets/videos/video4.mp4",
    "productUrl":
        "https://www.amazon.in/Amazon-Brand-Womens-Pleated-Knee-Long/dp/B086L77BTF",
    "productName": "Amazon Brand Skirt",
    "productDescription": "Eden & Ivy Cotton Pleated Skirt.",
    "currency": "₹",
    "priceBig": "290",
    "priceSmall": "",
    "shipping": "+ free shipping.",
    "taxes": "(incl. of all taxes)",
    "isLiked": false,
    "likes": "98 K",
    "isSaved": false,
    "saves": "15 K",
    "shares": "2 K",
  },
  {
    "videoUrl": "assets/videos/video5.mp4",
    "productUrl":
        "https://www.amazon.com/WAQIA-Portable-Ultrasonic-Business-39UGN5902BABK1ZLQDU5176A/dp/B08MWFMRK8/",
    "productName": "WAQIA Mini Washing Machine",
    "productDescription":
        "Portable USB Ultrasonic Turbine Washer for Travel or College dorms.",
    "currency": "\$",
    "priceBig": "27",
    "priceSmall": ".99",
    "shipping": "+ free shipping.",
    "taxes": "(excl. of taxes)",
    "isLiked": false,
    "likes": "2.2 M",
    "isSaved": false,
    "saves": "320 K",
    "shares": "80 K",
  },
  {
    "videoUrl": "assets/videos/video6.mp4",
    "productUrl":
        "https://in.sugarcosmetics.com/products/air-kiss-powder-lipstick",
    "productName": "Air Kiss Powder Lipstick",
    "productDescription":
        "Experience what magic feels like on your lips with Powder Lipstick.",
    "currency": "₹",
    "priceBig": "499",
    "priceSmall": "",
    "shipping": "",
    "taxes": "(incl. of all taxes)",
    "isLiked": false,
    "likes": "3.1 M",
    "isSaved": false,
    "saves": "120 K",
    "shares": "70 K",
  },
];
